#!/bin/sh
# 
# dmenu/awesome-menu program launcher
#
#----[ dmenu ]------------------------------------------------------------------------

#sh -c "$(exec `dmenu_path | dmenu -fn '-*-terminus-medium-r-normal-*-12-120-*-*-*-*-iso8859-1' -nb '#0a0a0a' -nf '#919191' -sb '#285577'` && exec $exe)"


#----[ awesome-menu ]-------------------------------------------------------

sh -c "$(exec ls -lL `echo /bin:/usr/bin:/usr/sbin:/usr/local/bin:/home/gig/bin:/sbin:/opt/mozilla/bin:/opt/java/jre/bin:/home/gig/hacks | sed 'y/:/ /'` | awk '$1 ~ /^[^d].*x/ && NF > 2 { print $NF }' | sort | uniq | awesome-menu -e 'exec ' 'Run:')"
