#!/bin/sh
# 
# dmenu/awesome-menu program launcher
#
#----[ dmenu ]------------------------------------------------------------

#sh -c "$(exec `dmenu_path | dmenu -fn '-*-terminus-medium-r-normal-*-12-120-*-*-*-*-iso8859-1' -nb '#0a0a0a' -nf '#919191' -sb '#285577'` && exec $exe)"


#----[ awesome-menu ]-----------------------------------------------------

sh -c "$(exec dmenu_path | awesome-menu -e 'exec ' 'Run:')"
