#!/bin/bash
#
# TODO: Make it possible to enter the WIDGET= as a launch parameter
# TODO: Make it display a table instead of one single line 
#
#--[ Configuration ]-----------------------------------------------------------------

BG='#0a0a0a'
FG='grey70'
FNT='-*-profont-*-*-*-*-11-*-*-*-*-*-iso8859-1'
XPOS=0
YPOS=14
WIDTH=1440
LINES=1
ACT='button1=togglecollapse;button3=exit'

# Widget to print info of (case sensitive):
# ALSA, Battery, Clock, CPUSpeed, CPUUsage, File, Filesystem, GMail, Maildir, Memory, MPD, MOC, NetTraffic, Raggle, Pacman, Weather.  
WIDGET='Weather'
OPT='locid' # Defined as options in widgetname.rb
VAR='BEXX0008' # Option value
FORMF='format' # Defined as fields in widget.name.rb
FORM='text #@temperature' # Format value

#------------------------------------------------------------------------------------

(echo `amazing -t$WIDGET "${OPT}: ${VAR}"`; \
sleep 5) | dzen2 -bg $BG -fg $FG -fn $FNT -x $XPOS -y $YPOS -w $WIDTH -l $LINES -sa c -e $ACT 
