#!/bin/bash
#
# (c) Gigamo 2008
#
# Requires scrot, imagemagick and ncftp
#     
#     Arch users can just "pacman -S scrot imagemagick ncftp" ;)
#
# Private version
#

#--[ Version number ]----------------------------------------------
version=0.3 #-- Add current/currentt.png    --    easier for forums 
#------------------------------------------------------------------

# Set to 1 to upload to FTP
ftpbool=1

# Set to 1 to display a link to the picture
linkbool=1

# Set to 1 to make a thumbnail
thumbbool=1

# Set the FTP host server
ftphost=""

# Set the FTP password
ftppath=""

# Set the FTP user
ftpuser=""

# Set the FTP password
ftppass=""

# The date...to append to the pic ;)
today=`date +"%d.%m.%y"`

# The actual path to the screenshot
datedpic=~/screenshots/desktop${today}.png
currentpic=~/screenshots/current.png

# The actual path to the thumbnail
datedthumb=~/screenshots/desktop${today}thumb.png
currentthumb=~/screenshots/currentt.png

link() {
  echo ""
  echo "Link to your freshly uploaded picture and thumbnail:";
  echo ""
  echo "http://$ftphost/gigamo/$ftppath/desktop${today}.png";
  if [ $thumbbool -eq 1 ] ; then
    echo "http://$ftphost/gigamo/$ftppath/desktop${today}thumb.png";
    echo ""
  else
    echo ""
  fi
}

printscreen() {
  `cd ~/screenshots && scrot desktop${today}.png`
  `cd ~/screenshots && cp desktop${today}.png current.png`
  if [ $thumbbool -eq 1 ] ; then
    `cd ~/screenshots && cp desktop${today}.png desktop${today}thumb.png`
    `cd ~/screenshots && mogrify -resize 25% desktop${today}thumb.png`
    `cd ~/screenshots && cp desktop${today}thumb.png currentt.png`
  else
    echo "Chosen not to make a thumbnail, skipping";
  fi
}

upload() {
  if [ $thumbbool -eq 1 ] ; then
    `ncftpput -u $ftpuser -p $ftppass -R -m $ftphost $ftppath $datedpic $currentpic $datedthumb $currentthumb`
  else
    `ncftpput -u $ftpuser -p $ftppass -R -m $ftphost $ftppath $datedpic $currentpic`
  fi
}

printscreen

case "$ftpbool" in
  '1')
    upload
    if [ $linkbool -eq 1 ] ; then
      link
    else
      echo "Chosen not to display image link, skipping";
    fi
    ;;
  '0')
    echo "Chosen not to upload to FTP, exiting";
    exit
    ;;
esac
