# Gigamo <gigamo@gmail.com> (15/04/08)
# Configuration file for amazing (http://github.com/dag/amazing)
# This particular config will only work with development version of awesome (version 2.3.rc1.1 and up!)
awesome:
    0:
        # Battery
        top battery: # top = statusbarid, battery = widgetid
            type: battery
            interval: 20
            format: |
                normcol = "\n0 widget_tell #@identifier fg #a0a0a0"
                urgcol = "\n0 widget_tell #@identifier fg #ff5656"
                case @state
                when :charging
                  "text  ^#{@percentage.to_i}^ #{normcol}"
                when :discharging
                  if @percentage <= 25
                    "text  v#{@percentage.to_i}v #{urgcol}"
                  else
                    "text  v#{@percentage.to_i}v #{normcol}"
                  end
                when :charged
                  "text  =#{@percentage.to_i}= #{normcol}"
                end
        # Clock
        top clock:
            type: clock
            interval: 1
            format: '"text  #@time "'
            time_format: "%H:%M:%S %d.%m.%Y"
        # CPU usage
        top cpu_usage:
            type: cpu_usage
            interval: 2
            format: |
                normcol = "%\n0 widget_tell #@identifier fg #ffffff"
                urgcol = "%\n0 widget_tell #@identifier fg #ff5656"
                if @usage[1].to_i >= 75 or @usage[2].to_i >= 75
                  "text  #{@usage[1].to_i}%/#{@usage[2].to_i}#{urgcol}"
                else
                  "text  #{@usage[1].to_i}%/#{@usage[2].to_i}#{normcol}"
                end
        # CPU frequency
        top cpu_freq:
            type: cpu_info # Can also be cpu info or cpu-info
            interval: 3
            format: |
                normcol = "\n0 widget_tell #@identifier fg #a0a0a0"
                urgcol = "\n0 widget_tell #@identifier fg #ff5656"
                if @speed[0] >= 1000
                  ghz = @speed[0] / 1000
                  "text  @ %3.2fGHz #{urgcol}" % ghz
                else
                  "text  @ %dMHz #{normcol}" % @speed[0]
                end
        # GMail
        top mail:
            type: gmail 
            interval: 300
            format: |
                normcol = "\n0 widget_tell #@identifier fg #ffffff"
                urgcol = "\n0 widget_tell #@identifier fg #ff5656"
                if @count == 0
                  "text  #@count #{normcol}"
                else
                  "text  #@count #{urgcol}"
                end
            username: username
            password: password
        # Pacman updates
        top pacman:
            type: pacman
            interval: 3600
            format: |
                normcol = "\n0 widget_tell #@identifier fg #ffffff"
                urgcol = "\n0 widget_tell #@identifier fg #ff5656"
                if @count == 0
                  "text #@count #{normcol}"
                else
                  "text #@count #{urgcol}"
                end
        # MPD
        top mpd:
            type: mpd
            interval: 1
            format: |
                case @state
                when :playing
                  "text  >>: #@artist - #@title (#{@position}/#{@length}) "
                when :paused
                  "text  ||: #@artist - #@title (#{@position}/#{@length}) "
                when :stopped
                  "text  []: not playing "
                end
